service: import-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: node-aws-course
  region: eu-west-3
  environment:
    IMPORT_AWS_REGION: ${env:IMPORT_AWS_REGION}
    IMPORT_BUCKET_NAME: ${env:IMPORT_BUCKET_NAME}
    IMPORT_UPLOADED_PREFIX: ${env:IMPORT_UPLOADED_PREFIX}
    IMPORT_SQS_URL: ${env:IMPORT_SQS_URL}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::aws-course-import-products"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::aws-course-import-products/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - "arn:aws:sqs:eu-west-3:935586505400:import-file-queue"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'

functions:
  importProductsFile:
    handler: src/handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/handlers/importFileParser.handler
    events:
      - s3:
          bucket: ${env:IMPORT_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:IMPORT_UPLOADED_PREFIX}
          existing: true
